[package]
name = "frust"
version = "0.1.0"
authors = ["Miles Egan <miles@plastaq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diacritics = "0.1.1"
glob = "0.3.0"
metaflac = "0.2"
opus_headers = "0.1.2"
unidecode = "0.3.0"
